config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/timofurrer/try:
      branch: master
      repo: https://github.com/timofurrer/try
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/timofurrer/try git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-zucchini-goose.sh
        container: qc.acc_grumpy-alizarin-bordeaux
  QC.Doc:
    repos:
      github.com/timofurrer/try find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cerise-pig.sh
        container: qc.doc_crappy-ochre-dog
      github.com/timofurrer/try git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-lilac-vulture.sh
        container: qc.doc_snappy-peach-dane
      github.com/timofurrer/try markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-khaki-liger.sh
        container: qc.doc_ugly-taupe-indri
      github.com/timofurrer/try restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-olivine-gar.sh
        container: qc.doc_lanky-malachite-tzu
  QC.Lic:
    repos:
      github.com/timofurrer/try licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-carmine-schnauzer.sh
        container: qc.lic_flabby-orchid-pinscher
  QC.Sec:
    repos:
      github.com/timofurrer/try bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-tangerine-rabbit.sh
        container: qc.sec_hasty-chestnut-collie
  QC.Sty:
    repos:
      github.com/timofurrer/try flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ruby-butterfly.sh
        container: qc.sty_wheezy-cream-antelope
  QC.Ver:
    repos:
      github.com/timofurrer/try get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-lavender-wildebeest.sh
        container: qc.ver_freaky-persimmon-penguin
timeout: 1800
